### ISSUE TITLE
How to login intro the Wordpress admin?

### ISSUE THREAD

**Issue by l2aelba** [assaf/zombie#1085]
I posted on http://stackoverflow.com/questions/40466711/how-to-login-intro-the-wordpress-admin but dont get any answer. So maybe its better to ask her ?

```javascript
describe('Wordpress Login', function() {
    const browser = new Browser();
    before(function() {
        return browser.visit(baseUrl+'wp-login.php');
    });

    describe('Submit form', function() {
        before(function() {
            browser.fill('#user_login', 'my_username').fill('#user_pass', 'my_password');
            return browser.pressButton('#wp-submit');
        });

        it('Should be successful', function() {
            console.log(browser.text('title')); // My Wordpress ‹ Log In
            //browser.assert.success();
        });
    });
});
```

When I do log by `browser.text('title')

its return **My Wordpress ‹ Log In** not **Dashboard ‹ My Wordpress**

That means it doesn't succeed. I try to use `wait()`, `then()`, `setTimeout()`before checking so its error like :

>     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

Any idea ?

**Comment by mdlavin** [comment]
You were right to use Stack Overflow instead of opening an issue. That site is a great place to get feedback about how to use the zombie library. Let's reserve the issues section of github for incorrect behavior that needs to be fixed.

I'll try to comment in stack overflow to help the question along. You also might want to give it some more time; it looks like it's only been open for < 1 day.

**Comment by l2aelba** [comment]
@mdlavin Thanks so much for this fix.

#1087 #1086
