### ISSUE TITLE
browser.close() not releasing memory

### ISSUE THREAD

**Issue by malterb** [assaf/zombie#672]
I am running into a big memory leakage problem with zombie.js while scraping a website. Each run adds about 20mb of ram usage. Running browser.close() is not reducing memory leakage.

var browser = new Browser();
browser.maxDuration = 15000;
browser.maxWait = 15000;
browser.visit('https://www.mywebsite.com',{ debug: true});
browser.wait(10000,function () {
     callback(browser.window); //callback processes the result successfully
}
browser.close();

Any idea way I can get node to release all memory used by this instance?

**Comment by PLPeeters** [comment]
This issue is still present and I think I've narrowed it down. In my case, `browser.deleteCookies()` wasn't working correctly and causing the memory leak. Doing this fixed the leak:

~~~
delete browser.cookies;
browser.deleteCookies();
~~~

Strangely enough, if I don't call the seemingly unnecessary `deleteCookies()` method after the `delete`, I get an empty reply  from the server on the next call.

**Comment by Bezronczek** [comment]
Hello,
I've found this Issue looking for solution for memory leaks in Zombie. I'm using it for processing a really big sites in order to automate process of verifying correct data (for example check for correct placement of element on each site) however I found out that after processing abour 150-200 URLs my computer runs out of memory as zombie is not releasing resources after finishing its work.
I see that you claim that zombie is not for webstie scraping however maybe you'll consider this use case as some sort of reason for implementing close() method which acutally kills the browser and frees the memory for next instances?

Cheers

**Comment by altsab** [comment]
Any news on the issue?

**Comment by panzupa** [comment]
I'm using Zombie in my lambda on Node.js 8.10.

My AWS **lambda** doesn't finish normally and **times out because of Zombie browser**.

```
const Browser = require('zombie');
  var browser = new Browser();

  const val = await new Promise((resolve, reject) => {
    browser.visit(url, () => {
      browser.fill('content-protector-password', pass)
      browser.pressButton('Submit', () => {
        const result = browser.html('div')
        browser.tabs.closeAll()
        resolve(result)
      })
    })
  })
  browser.destroy()
  delete browser
  return val
```
I'm not an expert but Zombie doesn't close and it's still in Lambda's EventLoop, that's why it times out. Any ideas how to stop/exit/quit/kill/destroy that browser? Or it never dies... like name suggestes?
