### ISSUE TITLE
Event manager

### ISSUE THREAD

**Issue by leetercola** [assaf/zombie#856]
I'd like to see implementation for wait/listen to events that are not dom related. Ideally you could pass an object like backbone.events to the wait function with a named event?

    browser.wait("customreadyevent",backbone.events)
        .then(function(){
        console.log('test some ajax content now');
    })

Would be triggered by 
    
    backbone.events.trigger('customreadyevent');

possibly with a config option for browser to define wait binding {listenCommand:"wait | on | fire"} which would support different event api's?

**Comment by assaf** [comment]
There's one DOM API so that's easy for Zombie to support. There's an endless number of client-side libraries, supporting all these APIs is not something that Zombie will ever do.

However, from your test code you can add an event listener to Backbone that sets a flag, and you can pass `wait` a function that will complete waiting once that flag is raised.
